FROM debian:13
ENV PATH="/root/.local/bin:$PATH"
RUN apt-get update -qq && \
    apt-get install -y -qq ca-certificates curl libvips python3 python3-venv python3-tk xvfb && \
    curl -LsSf https://astral.sh/uv/install.sh | sh && \
    uv python install 3.12
