#!/bin/bash
# Commands to test cdisplayagain performance realistically

echo "=== cdisplayagain Performance Testing Commands ==="
echo ""
echo "Enable performance logging:"
echo "  export CDISPLAYAGAIN_PERF=1"
echo ""
echo "1. Test CBZ launch with performance logging:"
echo "   export CDISPLAYAGAIN_PERF=1"
echo "   time uv run cdisplayagain.py tests/fixtures/test_cbz.cbz"
echo "   (Press q after first page loads, then view logs)"
echo ""
echo "2. Test CBR launch with performance logging:"
echo "   export CDISPLAYAGAIN_PERF=1"
echo "   time uv run cdisplayagain.py tests/fixtures/test_cbr.cbr"
echo "   (Press q after first page loads, then view logs)"
echo ""
echo "3. Run unit test with synchronous rendering:"
echo "   uv run --active pytest tests/test_performance.py::test_perf_launch_sample_comics -v -s --no-cov"
echo ""
echo "4. View performance logs:"
echo "   tail -f logs/\$(ls -t logs/ | head -1)/cdisplayagain.log | grep PERF"
echo ""
echo "5. Show all performance metrics from latest run:"
echo "   grep PERF logs/\$(ls -t logs/ | head -1)/cdisplayagain.log"
echo ""
